import type { Metadata } from "next";
import { pretendard } from "@/app/fonts";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ThemeToggle } from "@/components/ui/ThemeToggle";
import { Footer } from "@/components/ui/Footer";
import { ModalProvider } from "@/providers/ModalProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko" suppressHydrationWarning>
			<body className={`${pretendard.className}`} suppressHydrationWarning>
				<ThemeProvider>
					<ModalProvider>
						{children}
						{/* Theme Toggle - Fixed position */}
						<div className="fixed bottom-5 right-5">
							<ThemeToggle />
						</div>

						{/* Footer */}
						<Footer />
					</ModalProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
