import type { Metadata } from "next";
import { gmarketSans, pretendard } from "@/app/fonts";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ThemeToggle } from "@/components/ThemeToggle";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="ko"
			className={`${gmarketSans.variable} ${pretendard.variable}`}
			suppressHydrationWarning
		>
			<body className={`${pretendard.className}`} suppressHydrationWarning>
				<ThemeProvider>
					{children}
					{/* Footer */}
					<Footer />
					{/* Theme Toggle - Fixed position */}
					<div className="fixed bottom-5 right-5">
						<ThemeToggle />
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
