import { ObjectId } from "mongodb";

interface Group {
  _id: ObjectId; // Auto-generated by MongoDB
  name: string; // Required, e.g., "Design Team Feedback"
  description?: string;
  isPublic: boolean; // Default: true
  accessKey?: string; // Unique, short, human-readable key for private group access (e.g., from nanoid)
  // qrCodeLink will be generated dynamically: /group/qr/{accessKey} or similar
  managementPasswordHash: string; // Required, bcrypt hash of the management password
  tags?: string[]; // Tags defined by group admin for question categorization
  lastActivityAt: Date; // Updated on new questions/answers for sorting
  createdAt: Date;
  updatedAt: Date;
}