import { ObjectId } from "mongodb";

export interface DbGroup {
	_id: ObjectId; // Auto-generated by MongoDB
	name: string; // Required, e.g., "Design Team Feedback"
	description?: string;
	isPublic: boolean; // Default: true
	accessKey?: string; // Unique, short, human-readable key for private group access (e.g., from nanoid)
	// qrCodeLink will be generated dynamically: /group/qr/{accessKey} or similar
	managementPasswordHash: string; // Required, bcrypt hash of the management password
	questionCount: number; // Default: 0, denormalized for performance
	tags?: string[]; // Tags defined by group admin for question categorization
	lastActivityAt: Date; // Updated on new questions/answers for sorting
	createdAt: Date;
	updatedAt: Date;
}
